# Generated by Django 5.0.6 on 2024-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballers',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='footballers',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='footballers',
            index=models.Index(fields=['-time_create'], name='footballers_time_cr_105705_idx'),
        ),
    ]
