# Generated by Django 5.0.6 on 2024-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0002_alter_footballers_options_footballers_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballers',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
