# Generated by Django 5.0.6 on 2024-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0003_alter_footballers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballers',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
