# Generated by Django 5.0.6 on 2024-07-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0005_category_footballers_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballers',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballers.category'),
        ),
    ]
