# Generated by Django 5.0.6 on 2024-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0008_wife_footballers_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
