# Generated by Django 5.0.6 on 2024-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0009_wife_m_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='footballers',
            options={'ordering': ['-time_create'], 'verbose_name_plural': 'Footballers'},
        ),
        migrations.AlterField(
            model_name='footballers',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='footballers',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL:'),
        ),
        migrations.AlterField(
            model_name='footballers',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Оглавление:'),
        ),
    ]
