# Generated by Django 5.0.6 on 2024-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0011_footballers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballers',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/', verbose_name='Фото'),
        ),
    ]
